#!/usr/bin/env python3
"""Builds the French page, fr/index.html, from index.html + i18n/fr.json.

index.html is the only markup. Every element with data-i18n="key" gets its
contents replaced by the French for that key, every data-i18n-label="key"
its aria-label, and the head/toggle/links are pointed at /fr/. Fails loudly
if a key has no French or a replacement no longer matches, so copy edits in
index.html can't silently ship stale French.

Run after any change to index.html or i18n/fr.json, then commit both pages.
"""
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FR = json.loads((ROOT / 'i18n/fr.json').read_text(encoding='utf-8'))
src = (ROOT / 'index.html').read_text(encoding='utf-8')
used = set()


def fr(key):
    if key not in FR:
        sys.exit(f'build-fr: no French for "{key}" in i18n/fr.json')
    used.add(key)
    return FR[key]


def swap_contents(s):
    """Replace the inner HTML of every data-i18n element, respecting nesting."""
    out, pos = [], 0
    opener = re.compile(r'<([a-zA-Z][a-zA-Z0-9]*)\b[^>]*\sdata-i18n="([^"]+)"[^>]*>')
    while m := opener.search(s, pos):
        tag, key = m.group(1), m.group(2)
        depth, i = 1, m.end()
        tags = re.compile(rf'<(/?){tag}\b[^>]*>', re.I)
        while depth:
            t = tags.search(s, i)
            if not t:
                sys.exit(f'build-fr: unclosed <{tag} data-i18n="{key}">')
            depth += -1 if t.group(1) else 1
            i = t.end()
        out += [s[pos:m.end()], fr(key)]
        pos = t.start()
    return ''.join(out) + s[pos:]


def swap_labels(s):
    def one(m):
        key = re.search(r'data-i18n-label="([^"]+)"', m.group(0)).group(1)
        return re.sub(r'aria-label="[^"]*"', 'aria-label="%s"' % html.escape(fr(key)), m.group(0))
    return re.sub(r'<[^>]*\sdata-i18n-label="[^"]+"[^>]*>', one, s)


def replace(s, old, new, count=1):
    n = s.count(old)
    if n != count:
        sys.exit(f'build-fr: expected {count} match(es), found {n}: {old[:80]!r}')
    return s.replace(old, new)


def meta(s, attr, name, value):
    pat = re.compile(rf'(<meta {attr}="{re.escape(name)}" content=")[^"]*(")')
    s, n = pat.subn(lambda m: m.group(1) + html.escape(value) + m.group(2), s)
    if n != 1:
        sys.exit(f'build-fr: meta {name} not found')
    return s


s = swap_labels(swap_contents(src))

s = replace(s, '<!DOCTYPE html>\n<html lang="en">',
            '<!DOCTYPE html>\n<!-- Generated by scripts/build-fr.py from index.html + i18n/fr.json. Edit those, not this file. -->\n<html lang="fr-CA">')
s = re.sub(r'<script id="lang-redirect">.*?</script>\n', '', s, flags=re.S)
s = re.sub(r'<!-- French-first browsers.*?-->\n', '', s, flags=re.S)
s = re.sub(r'<title>.*?</title>', '<title>%s</title>' % html.escape(fr('meta.title'), quote=False), s)
s = meta(s, 'name', 'description', fr('meta.desc'))
s = meta(s, 'property', 'og:title', fr('meta.title'))
s = meta(s, 'property', 'og:description', fr('meta.desc'))
s = meta(s, 'property', 'og:image:alt', fr('meta.ogAlt'))
s = meta(s, 'name', 'twitter:title', fr('meta.title'))
s = meta(s, 'name', 'twitter:description', fr('meta.twDesc'))
s = replace(s, '<meta property="og:url" content="https://manndev.com/">', '<meta property="og:url" content="https://manndev.com/fr/">')
s = replace(s, '<link rel="canonical" href="https://manndev.com/">', '<link rel="canonical" href="https://manndev.com/fr/">')
s = replace(s, '<meta property="og:locale" content="en_CA">\n<meta property="og:locale:alternate" content="fr_CA">',
            '<meta property="og:locale" content="fr_CA">\n<meta property="og:locale:alternate" content="en_CA">')
s = replace(s, '<a href="https://manndev.com/" class=', '<a href="https://manndev.com/fr/" class=', count=2)
s = replace(s, '<a href="/fr/" class="nav-lang" id="lang-toggle" data-lang="fr" hreflang="fr" lang="fr" aria-label="Français">FR</a>',
            '<a href="/" class="nav-lang" id="lang-toggle" data-lang="en" hreflang="en" lang="en" aria-label="English">EN</a>')
s = replace(s, '/img/process-film', '/img/process-film-fr', count=3)   # poster, webm, mp4 (scripts/render-film.mjs fr)
s = replace(s, 'name="language" id="language-field" value="English"', 'name="language" id="language-field" value="Français"')
s = re.sub(r' data-i18n(?:-label)?="[^"]*"', '', s)

unused = sorted(set(FR) - used - {'meta.title', 'meta.desc', 'meta.ogAlt', 'meta.twDesc'})
if unused:
    print('build-fr: unused keys in i18n/fr.json: ' + ', '.join(unused))

(ROOT / 'fr').mkdir(exist_ok=True)
(ROOT / 'fr/index.html').write_text(s, encoding='utf-8')
print(f'Built fr/index.html ({len(used)} strings). Commit and push, then \'git pull\' on the server.')
